package kmp.shared.samplecomposemultiplatform.presentation.ui

// Originally generated by Touchlab's [compose-swift-bridge]
typealias SampleComposeMultiplatformViewFactory =
    ComposeSampleComposeMultiplatformViewFactory

expect interface ComposeSampleComposeMultiplatformViewFactory
