package kmp.shared.samplecomposemultiplatform.presentation.ui

import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.compositionLocalOf

// Originally generated by Touchlab's [compose-swift-bridge]
val LocalSampleComposeMultiplatformViewFactory: ProvidableCompositionLocal<ComposeSampleComposeMultiplatformViewFactory> =
    compositionLocalOf(
        defaultFactory = {
            error(
                """You have to provide LocalSampleComposeMultiplatformViewFactory""",
            )
        },
    )
