package kmp.shared.samplecomposemultiplatform.presentation.ui

// Originally generated by Touchlab's [compose-swift-bridge]
interface PlatformSpecificCheckboxViewDelegate {
    fun updateText(text: String)
    fun updateChecked(checked: Boolean)
    fun updateOnCheckedChanged(onCheckedChanged: (Boolean) -> Unit)
}
