name: Android – PR Check

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint:
    name: Lint & Build
    runs-on: [self-hosted, pikachu]
    container:
      image: mateedevs/charmander-emulator
      options: --privileged
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run lint
        run: |
          ./gradlew ktlintCheck

      - name: Run architecture lint
        run: |
          ./gradlew :shared:core:testAlphaDebugUnitTest --tests "konsistTest.*" --no-build-cache --no-configuration-cache

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/testAlphaDebugUnitTest/TEST-*.xml'

      - name: Build
        run: |
          ./gradlew generateTwine
          ./gradlew :android:app:bundleDebug
          
      - name: UI tests
        run: |
          start_emu_headless.sh
          ./gradlew :android:app:connectedCheck
