name: iOS - Build develop

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    name: Create new build
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, ios-build]
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          clean: false
      - name: Setup tools
        working-directory: ios
        run: ./scripts/setup.sh
      - name: Generate build number
        run: echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
      - name: Prepare App Store Connect API key file
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        working-directory: ios
        run: echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > AuthKey_Matee.p8
      - name: Create a new Alpha build
        env:
          BUILD_NUMBER: $(echo `date +"%y%m%d%H%M"`)
        working-directory: ios
        run: fastlane build_alpha

  deploy-alpha:
    name: Deploy alpha
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: [self-hosted, ios-internal]
    timeout-minutes: 15
    steps:
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
          DISTRIBUTE_EXTERNAL: false
        working-directory: ios
        run: fastlane upload_testflight_alpha distribute_external:false
